
# travis test, not jet working/complete

dist: bionic
language: cpp
compiler: gcc

before_script:
    - mkdir build
    - cd build
    - cmake -DSNAKEOIL_TARGET_GRAPHICS_API=null ..

script:
    - make